### ISSUE TITLE
How to create "compareStreams" workflow using Python requests?

### ISSUE THREAD

**Issue by vasily-v-ryabov** [ebu/pi-list#134]
Hi, I'm trying to create comparison of 2 video streams using REST API through Python `requests`. I can get pcap_id and stream_id successfully, but I faced with insufficient docs about workflow and comparisons APIs.

What I'm trying with `/api/workflow/`:
```python
    def compare_streams(self, ref_stream, main_stream, user_folder):
        data = {
            "name": "name123",
            "type": "compareStreams",
            "config": {
                "comparison_type": "psnrAndDelay",
                "user_folder": user_folder,
                "main": {
                    "pcap": main_stream['pcap'],
                    "stream": main_stream['id'],
                    "media_type": main_stream['media_type'],
                },
                "reference": {
                    "pcap": ref_stream['pcap'],
                    "stream": ref_stream['id'],
                    "media_type": ref_stream['media_type'],
                },
                "media_type": main_stream['media_type'],
                "media_specific": main_stream['media_specific'],
            },
        }
        r = requests.post(
            urlparse.urljoin(self.base_url, 'api/workflow/'),
            data=data,
            headers={'Authorization': 'Bearer {}'.format(self.token)}
        )
        if not r.ok:
            raise Exception('Failed to compare! Status code: {}, reason: "{}"'.format(r.status_code, r.reason))
        return r.json()
```

I get 500 Internal Server Error with the following logs in local docker-compose output (I use latest version):
```
listserver_1  | 2021-09-28T13:33:25.580Z [workflow-api] info: Create workflow request for undefined
listserver_1  | 2021-09-28T13:33:25.581Z [express-middleware] error: TypeError: Cannot set property 'authorization' of undefined
listserver_1  |     at /app/listwebserver/api/workflow.js:17:33
listserver_1  |     at Layer.handle [as handle_request] (/app/listwebserver/node_modules/express/lib/router/layer.js:95:5)
listserver_1  |     at next (/app/listwebserver/node_modules/express/lib/router/route.js:137:13)
listserver_1  |     at Route.dispatch (/app/listwebserver/node_modules/express/lib/router/route.js:112:3)
listserver_1  |     at Layer.handle [as handle_request] (/app/listwebserver/node_modules/express/lib/router/layer.js:95:5)
listserver_1  |     at /app/listwebserver/node_modules/express/lib/router/index.js:281:22
listserver_1  |     at Function.process_params (/app/listwebserver/node_modules/express/lib/router/index.js:335:12)
listserver_1  |     at next (/app/listwebserver/node_modules/express/lib/router/index.js:275:10)
listserver_1  |     at Function.handle (/app/listwebserver/node_modules/express/lib/router/index.js:174:3)
listserver_1  |     at router (/app/listwebserver/node_modules/express/lib/router/index.js:47:12)
listserver_1  |     at Layer.handle [as handle_request] (/app/listwebserver/node_modules/express/lib/router/layer.js:95:5)
listserver_1  |     at trim_prefix (/app/listwebserver/node_modules/express/lib/router/index.js:317:13)
listserver_1  |     at /app/listwebserver/node_modules/express/lib/router/index.js:284:7
listserver_1  |     at Function.process_params (/app/listwebserver/node_modules/express/lib/router/index.js:335:12)
listserver_1  |     at next (/app/listwebserver/node_modules/express/lib/router/index.js:275:10)
listserver_1  |     at Function.handle (/app/listwebserver/node_modules/express/lib/router/index.js:174:3)
listserver_1  |     at router (/app/listwebserver/node_modules/express/lib/router/index.js:47:12)
listserver_1  |     at Layer.handle [as handle_request] (/app/listwebserver/node_modules/express/lib/router/layer.js:95:5)
listserver_1  |     at trim_prefix (/app/listwebserver/node_modules/express/lib/router/index.js:317:13)
listserver_1  |     at /app/listwebserver/node_modules/express/lib/router/index.js:284:7
listserver_1  |     at Function.process_params (/app/listwebserver/node_modules/express/lib/router/index.js:335:12)
listserver_1  |     at next (/app/listwebserver/node_modules/express/lib/router/index.js:275:10)
listserver_1  | 2021-09-28T13:33:25.583Z [rest-api] info: ::ffff:172.18.0.5 - POST /api/workflow/ HTTP/1.0 500 2132 - 3.122 ms
```

In normal case (when comparing streams manually) I see the following logs:
```
listserver_1  | 2021-09-28T10:53:43.660Z [workflow-api] info: Create workflow request for compareStreams
listserver_1  | 2021-09-28T10:53:43.661Z [workflow-controller] info: Creating workflow 592071d0-204a-11ec-80b1-f1f804a9b5db of type compareStreams
listserver_1  | 2021-09-28T10:53:43.664Z [rest-api] info: ::ffff:172.18.0.5 - POST /api/workflow/ HTTP/1.0 200 - - 2.689 ms
listserver_1  | 2021-09-28T10:53:43.669Z [compare-streams] info: Config: {"comparison_type":"psnrAndDelay","user_folder":"/home//691a50c0-2044-11ec-80b1-f1f804a9b5db","main":{"pcap":"b7732325-1071-4690-9ff1-185c6639dc0f","stream":"1941d04a-c7d3-4813-a2a8-4eed087261a3","media_type":"video"},"reference":{"pcap":"92f1c183-4a08-4407-957f-e515b9544b11","stream":"8a9bace5-9bc5-4dbd-9486-08742cd448e7","media_type":"video"},"media_type":"video","media_specific":{"avg_tro_ns":627130,"color_depth":10,"colorimetry":"BT709","has_continuation_bit_set":false,"height":1080,"max_tro_ns":632757,"min_tro_ns":622593,"packets_per_frame":4320,"packing_mode":1,"rate":"60","sampling":"YCbCr-4:2:2","scan_type":"progressive","schedule":"gapped","tro_default_ns":637037,"width":1920}}
listserver_1  | 2021-09-28T10:53:43.669Z [workflow-controller] info: Added workflow 592071d0-204a-11ec-80b1-f1f804a9b5db of type compareStreams
listserver_1  | 2021-09-28T10:53:43.786Z [psnr-delay] info: Compare 82 frames of main sequence with frame #41 of reference sequence.
listserver_1  | 2021-09-28T10:53:51.374Z [psnr-delay] info: Compare 80 frames of main sequence with 80 frames of shifted reference sequence, one to one.
listserver_1  | 2021-09-28T10:53:58.525Z [psnr-delay] info: {"comparison_type":"psnrAndDelay","user_folder":"/home//691a50c0-2044-11ec-80b1-f1f804a9b5db","main":{"pcap":"b7732325-1071-4690-9ff1-185c6639dc0f","stream":"1941d04a-c7d3-4813-a2a8-4eed087261a3","media_type":"video"},"reference":{"pcap":"92f1c183-4a08-4407-957f-e515b9544b11","stream":"8a9bace5-9bc5-4dbd-9486-08742cd448e7","media_type":"video"},"media_type":"video","media_specific":{"avg_tro_ns":627130,"color_depth":10,"colorimetry":"BT709","has_continuation_bit_set":false,"height":1080,"max_tro_ns":632757,"min_tro_ns":622593,"packets_per_frame":4320,"packing_mode":1,"rate":"60","sampling":"YCbCr-4:2:2","scan_type":"progressive","schedule":"gapped","tro_default_ns":637037,"width":1920}}
listserver_1  | 2021-09-28T10:53:58.525Z [psnr-delay] info: ref frame: {"index":41,"path":"/home/691a50c0-2044-11ec-80b1-f1f804a9b5db/92f1c183-4a08-4407-957f-e515b9544b11/8a9bace5-9bc5-4dbd-9486-08742cd448e7/1474830395","rtp_ts":1474830395,"first_packet_ts":1626615945717297200,"last_packet_ts":1626615945733290000}
listserver_1  | 2021-09-28T10:53:58.526Z [psnr-delay] info: psnr max: {"psnr":"inf","index":41}
listserver_1  | 2021-09-28T10:53:58.526Z [psnr-delay] info: main frame: {"index":41,"path":"/home/691a50c0-2044-11ec-80b1-f1f804a9b5db/b7732325-1071-4690-9ff1-185c6639dc0f/1941d04a-c7d3-4813-a2a8-4eed087261a3/1474830395","rtp_ts":1474830395,"first_packet_ts":1626615945717297400,"last_packet_ts":1626615945733290500}
listserver_1  | 2021-09-28T10:53:58.526Z [psnr-delay] info: delays : {"sample":0,"rtp":0,"actual":0.384}
listserver_1  | 2021-09-28T10:53:58.526Z [psnr-delay] info: media: {"sign":1,"frames":0,"fields":0,"lines":0,"pixels":47}
listserver_1  | 2021-09-28T10:53:58.634Z [rest-api] info: ::ffff:172.18.0.5 - GET /api/comparisons HTTP/1.0 200 1543 - 4.377 ms
```

I also tried to add `"type": "compareStreams"` to header, but it doesn't work also (the same logs). What am I doing wrong?

**Comment by vasily-v-ryabov** [comment]
Hmm... When I wrapped `data` into ` json.dumps(...)` and added `'Content-type': 'application/json'` to headers, I get a bit better logs, but it still fails with authorization:
```
listserver_1  | 2021-09-28T14:53:43.064Z [workflow-api] info: Create workflow request for compareStreams
listserver_1  | 2021-09-28T14:53:43.065Z [express-middleware] error: TypeError: Cannot set property 'authorization' of undefined
listserver_1  |     at /app/listwebserver/api/workflow.js:17:33
listserver_1  |     at Layer.handle [as handle_request] (/app/listwebserver/node_modules/express/lib/router/layer.js:95:5)
listserver_1  |     at next (/app/listwebserver/node_modules/express/lib/router/route.js:137:13)
listserver_1  |     at Route.dispatch (/app/listwebserver/node_modules/express/lib/router/route.js:112:3)
listserver_1  |     at Layer.handle [as handle_request] (/app/listwebserver/node_modules/express/lib/router/layer.js:95:5)
listserver_1  |     at /app/listwebserver/node_modules/express/lib/router/index.js:281:22
listserver_1  |     at Function.process_params (/app/listwebserver/node_modules/express/lib/router/index.js:335:12)
listserver_1  |     at next (/app/listwebserver/node_modules/express/lib/router/index.js:275:10)
listserver_1  |     at Function.handle (/app/listwebserver/node_modules/express/lib/router/index.js:174:3)
listserver_1  |     at router (/app/listwebserver/node_modules/express/lib/router/index.js:47:12)
listserver_1  |     at Layer.handle [as handle_request] (/app/listwebserver/node_modules/express/lib/router/layer.js:95:5)
listserver_1  |     at trim_prefix (/app/listwebserver/node_modules/express/lib/router/index.js:317:13)
listserver_1  |     at /app/listwebserver/node_modules/express/lib/router/index.js:284:7
listserver_1  |     at Function.process_params (/app/listwebserver/node_modules/express/lib/router/index.js:335:12)
listserver_1  |     at next (/app/listwebserver/node_modules/express/lib/router/index.js:275:10)
listserver_1  |     at Function.handle (/app/listwebserver/node_modules/express/lib/router/index.js:174:3)
listserver_1  |     at router (/app/listwebserver/node_modules/express/lib/router/index.js:47:12)
listserver_1  |     at Layer.handle [as handle_request] (/app/listwebserver/node_modules/express/lib/router/layer.js:95:5)
listserver_1  |     at trim_prefix (/app/listwebserver/node_modules/express/lib/router/index.js:317:13)
listserver_1  |     at /app/listwebserver/node_modules/express/lib/router/index.js:284:7
listserver_1  |     at Function.process_params (/app/listwebserver/node_modules/express/lib/router/index.js:335:12)
listserver_1  |     at next (/app/listwebserver/node_modules/express/lib/router/index.js:275:10)
listserver_1  | 2021-09-28T14:53:43.066Z [rest-api] info: ::ffff:172.18.0.5 - POST /api/workflow/ HTTP/1.0 500 2132 - 10.203 ms
```

**Comment by vasily-v-ryabov** [comment]
After changing `"config"` to `"configuration"` in the input data it fails later now:
```
listserver_1  | 2021-09-28T15:00:13.828Z [workflow-api] info: Create workflow request for compareStreams
listserver_1  | 2021-09-28T15:00:13.829Z [workflow-controller] info: Creating workflow c8c0d440-206c-11ec-80b1-f1f804a9b5db of type compareStreams
listserver_1  | 2021-09-28T15:00:13.831Z [rest-api] info: ::ffff:172.18.0.5 - POST /api/workflow/ HTTP/1.0 200 - - 5.209 ms
listserver_1  | 2021-09-28T15:00:13.877Z [undefined] error: Cannot read property 'pcap' of null
listserver_1  | 2021-09-28T15:00:13.878Z [workflow-controller] error: Error creating workflow: Cannot read property 'pcap' of null
listserver_1  | (node:63) UnhandledPromiseRejectionWarning: TypeError: Error creating workflow: Cannot read property 'pcap' of null
listserver_1  |     at getConfig (/app/listwebserver/controllers/workflow/compareStreams.js:17:24)
listserver_1  |     at runMicrotasks (<anonymous>)
listserver_1  |     at processTicksAndRejections (internal/process/task_queues.js:97:5)
listserver_1  |     at async createWorkflow (/app/listwebserver/controllers/workflow/compareStreams.js:109:25)
listserver_1  |     at async doCreateWorkflow (/app/listwebserver/controllers/workflow/index.js:144:9)
listserver_1  |     at async Object.createWorkflow (/app/listwebserver/controllers/workflow/index.js:195:9)
listserver_1  | (node:63) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
listserver_1  | (node:63) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by vasily-v-ryabov** [comment]
Error message doesn't tell about the missing field that is null and it should contain attribute 'pcap'. I could find the parent field name in JS code. Please advise.

**Comment by vasily-v-ryabov** [comment]
OK, with below data it could create a workflow, but comparison is failed.

The data:
```
        data = json.dumps({
            "name": "name123",
            "type": "compareStreams",
            "configuration": {
                "mainStreamID": main_stream['id'],
                "refStreamID": ref_stream['id'],
                "comparison_type": "psnrAndDelay",
                "user_folder": user_folder,
                "main": {
                    "pcap": main_stream['pcap'],
                    "stream": main_stream['id'],
                    "media_type": main_stream['media_type'],
                },
                "ref": {
                    "pcap": ref_stream['pcap'],
                    "stream": ref_stream['id'],
                    "media_type": ref_stream['media_type'],
                },
                "media_type": main_stream['media_type'],
                "media_specific": main_stream['media_specific'],
            },
        })
```
The logs:
```
listserver_1  | 2021-09-28T16:53:57.516Z [workflow-api] info: Create workflow request for compareStreams
listserver_1  | 2021-09-28T16:53:57.517Z [workflow-controller] info: Creating workflow abfd23d0-207c-11ec-80b1-f1f804a9b5db of type compareStreams
listserver_1  | 2021-09-28T16:53:57.519Z [rest-api] info: ::ffff:172.18.0.5 - POST /api/workflow/ HTTP/1.0 200 - - 6.083 ms
listserver_1  | 2021-09-28T16:53:57.548Z [compare-streams] info: Config: {"comparison_type":"psnrAndDelay","user_folder":"/home//691a50c0-2044-11ec-80b1-f1f804a9b5db","main":{"pcap":"632486d0-e536-4026-9e3c-bf8ae742b674","stream":"5425f314-a93b-4f0e-bb15-8ef0e8e357f7","media_type":"video"},"reference":{"pcap":"855623eb-87d8-4589-a0f5-ef30f7f2a22c","stream":"96700e43-f677-4455-89b9-b69dfbf3b4cf","media_type":"video"},"media_type":"video","media_specific":{"avg_tro_ns":627130,"color_depth":10,"colorimetry":"BT709","has_continuation_bit_set":false,"height":1080,"max_tro_ns":632757,"min_tro_ns":622593,"packets_per_frame":4320,"packing_mode":1,"rate":"60","sampling":"YCbCr-4:2:2","scan_type":"progressive","schedule":"gapped","tro_default_ns":637037,"width":1920}}
listserver_1  | 2021-09-28T16:53:57.549Z [workflow-controller] info: Added workflow abfd23d0-207c-11ec-80b1-f1f804a9b5db of type compareStreams
listserver_1  | 2021-09-28T16:53:57.723Z [psnr-delay] info: Compare 82 frames of main sequence with frame #41 of reference sequence.
listserver_1  | 2021-09-28T16:54:04.938Z [psnr-delay] info: Compare 80 frames of main sequence with 80 frames of shifted reference sequence, one to one.
listserver_1  | 2021-09-28T16:54:12.956Z [psnr-delay] info: {"comparison_type":"psnrAndDelay","user_folder":"/home//691a50c0-2044-11ec-80b1-f1f804a9b5db","main":{"pcap":"632486d0-e536-4026-9e3c-bf8ae742b674","stream":"5425f314-a93b-4f0e-bb15-8ef0e8e357f7","media_type":"video"},"reference":{"pcap":"855623eb-87d8-4589-a0f5-ef30f7f2a22c","stream":"96700e43-f677-4455-89b9-b69dfbf3b4cf","media_type":"video"},"media_type":"video","media_specific":{"avg_tro_ns":627130,"color_depth":10,"colorimetry":"BT709","has_continuation_bit_set":false,"height":1080,"max_tro_ns":632757,"min_tro_ns":622593,"packets_per_frame":4320,"packing_mode":1,"rate":"60","sampling":"YCbCr-4:2:2","scan_type":"progressive","schedule":"gapped","tro_default_ns":637037,"width":1920}}
listserver_1  | 2021-09-28T16:54:12.956Z [psnr-delay] info: ref frame: {"index":41,"path":"/home/691a50c0-2044-11ec-80b1-f1f804a9b5db/855623eb-87d8-4589-a0f5-ef30f7f2a22c/96700e43-f677-4455-89b9-b69dfbf3b4cf/1474830395","rtp_ts":1474830395,"first_packet_ts":1626615945717297200,"last_packet_ts":1626615945733290000}
listserver_1  | 2021-09-28T16:54:12.956Z [psnr-delay] info: psnr max: {"psnr":"inf","index":41}
listserver_1  | 2021-09-28T16:54:12.957Z [psnr-delay] info: main frame: {"index":41,"path":"/home/691a50c0-2044-11ec-80b1-f1f804a9b5db/632486d0-e536-4026-9e3c-bf8ae742b674/5425f314-a93b-4f0e-bb15-8ef0e8e357f7/1474830395","rtp_ts":1474830395,"first_packet_ts":1626615945717297400,"last_packet_ts":1626615945733290500}
listserver_1  | 2021-09-28T16:54:12.957Z [psnr-delay] info: delays : {"sample":0,"rtp":0,"actual":0.384}
listserver_1  | 2021-09-28T16:54:12.957Z [psnr-delay] info: media: {"sign":1,"frames":0,"fields":0,"lines":0,"pixels":47}
listserver_1  | 2021-09-28T16:54:12.963Z [undefined] error: streamCompare validation failed: name: Path `name` is required.
```

**Comment by vasily-v-ryabov** [comment]
Well, finally I made it working with this:
```
        data = json.dumps({
            "name": "name123",
            "type": "compareStreams",
            "configuration": {
                "mainStreamID": main_stream['id'],
                "refStreamID": ref_stream['id'],
                "name": "name123",
                "comparison_type": "psnrAndDelay",
                "media_specific": main_stream['media_specific'],
            },
        })
```

**Comment by pedro-alves-ferreira** [comment]
Hi Vasily,

I'm sorry we couldn't reply earlier but I'm glad you got it to work. Let us know if you need further help.

Best regards,

Pedro
